# Copyright Â© 2018 Booz Allen Hamilton. All Rights Reserved.
# This software package is licensed under the Booz Allen Public License. The license can be found in the License file or at http://boozallen.github.io/licenses/bapl

global:
  domain: apps.ocp.myuscis-tech-challenge # Set this to the domain of your Openshift routes (or K8's services)
  # Configure any other global variables (e.g. openshift, persistentStorage) below

# something
jenkins:
  githubOrganizations: # Replace the example below with the GitHub Organizations the pipeline should serve
  - name: Red-Hat-Summit
    displayName: "Red Hat Summit"
    credentialID: github
    apiUrl: "https://github.boozallencsn.com/api/v3"
  pipelineLibraries: # Replace the example below with the pipeline config libraries you want to make available
  - name: red-hat-summit
    githubApiUrl: "https://github.boozallencsn.com/api/v3"
    githubCredentialID: github
    org: Red-Hat-Summit
    repo: pipeline-configuration

  # Replace the username and password below with your GitHub username and
  # access token, then add any additional credentials you need
  credentials:
  - id: "github"
    username: "username"
    password: "password"
  # Configure additional Jenkins variables as necessary

sonarqube:
  enabled: true

selenium:
  enabled: true
