# Copyright Â© 2018 Booz Allen Hamilton. All Rights Reserved.
# This software package is licensed under the Booz Allen Public License. The license can be found in the License file or at http://boozallen.github.io/licenses/bapl

kind: ConfigMap
apiVersion: v1
metadata:
  name: jenkins-job-dsl
  namespace: {{ .Release.Namespace }}
  labels:
    app: jenkins
data:
  job-dsl: |
    {{- range .Values.githubOrganizations }}
    try{
      githubOrg = {{ required "Required property .Values.githubOrganizations.name missing" .name | quote}}
      credId = {{ required "Required property .Values.githubOrganizations.credentialID missing" .credentialID | quote }}
      apiUri = {{ required "Required property .Values.githubOrganizations.apiUrl missing" .apiUrl | quote }}
      patternInclude = {{ .repoPattern | default ".*" | quote }}
      patternExclude = ""
      scriptPath = {{ .entrypointScriptPath | default "resources/sdp/pipeline_entrypoint" | quote }}
      sandbox = {{ .sanbox | default false }}
      entrypointRepo = {{ .entrypointRepo | default "https://github.com/boozallen/sdp-helm-chart" | quote }}
      entrypointRepoCredId = {{ .entrypointRepoCredId | default .credentialID | quote }}

      organizationFolder githubOrg, {
        projectFactories{}
        configure{
          it / navigators << 'org.jenkinsci.plugins.github__branch__source.GitHubSCMNavigator'{
            repoOwner githubOrg
            scanCredentialsId credId
            checkoutCredentialsId 'SAME'
            apiUri apiUri
            buildOriginBranch true
            buildOriginBranchWithPR false
            buildOriginPRMerge true
            buildOriginPRHead false
            buildForkPRMerge false
            buildForkPRHead false
            traits << 'jenkins.scm.impl.trait.WildcardSCMSourceFilterTrait'{
              includes patternInclude
              excludes patternExclude
            }
          }
          it / projectFactories << "org.jenkinsci.plugins.common.workflow.ScmBasedCommonWorkflowMultiBranchProjectFactory"{
            scriptPath scriptPath
            sandbox sandbox
            lightweight true
            scm (class: 'hudson.plugins.git.GitSCM'){
              configVersion 2
              userRemoteConfigs{
                'hudson.plugins.git.UserRemoteConfig' {
                  url entrypointRepo
                  credentialsId entrypointRepoCredId
                }
              }
              branches{
                'hudson.plugins.git.BranchSpec'{
                  name "*/master"
                }
              }
            }
          }
        }
      }
    }catch(any){}
    {{- end }}
