# Copyright Â© 2018 Booz Allen Hamilton. All Rights Reserved.
# This software package is licensed under the Booz Allen Public License. The license can be found in the License file or at http://boozallen.github.io/licenses/bapl

{{- if .Values.global.openshift }}
kind: ImageStream
apiVersion: "image.openshift.io/v1"
metadata:
  name: jenkins-agent
  namespace: {{ .Release.Namespace }}
{{- end }}